package com.restaurant.model;

import org.socialsignin.spring.data.dynamodb.mapping.DynamoDBHashKey;
import org.socialsignin.spring.data.dynamodb.mapping.DynamoDBTable;
import org.socialsignin.spring.data.dynamodb.mapping.DynamoDBAttribute;
import org.socialsignin.spring.data.dynamodb.mapping.DynamoDBAutoGeneratedKey;

@DynamoDBTable(tableName = "feedbacks")
public class Feedback {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private Long id;

    @DynamoDBAttribute
    private String comment;

    @DynamoDBAttribute
    private int rating;

    @DynamoDBAttribute
    private String locationId;

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public String getLocationId() {
        return locationId;
    }

    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }
}