package com.restaurant.model;

import org.socialsignin.spring.data.dynamodb.mapping.DynamoDBHashKey;
import org.socialsignin.spring.data.dynamodb.mapping.DynamoDBTable;
import org.socialsignin.spring.data.dynamodb.mapping.DynamoDBAttribute;
import org.socialsignin.spring.data.dynamodb.mapping.DynamoDBAutoGeneratedKey;

import java.util.List;

@DynamoDBTable(tableName = "locations")
public class Location {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String address;

    @DynamoDBAttribute
    private List<SpecialityDish> specialityDishes;

    @DynamoDBAttribute
    private List<Feedback> feedbacks;

    // Getters and Setters
}