package com.restaurant.model;

import org.socialsignin.spring.data.dynamodb.mapping.DynamoDBHashKey;
import org.socialsignin.spring.data.dynamodb.mapping.DynamoDBTable;
import org.socialsignin.spring.data.dynamodb.mapping.DynamoDBAttribute;
import org.socialsignin.spring.data.dynamodb.mapping.DynamoDBAutoGeneratedKey;

import java.util.List;

@DynamoDBTable(tableName = "locations")
public class Location {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String address;

    @DynamoDBAttribute
    private List<SpecialityDish> specialityDishes;

    @DynamoDBAttribute
    private List<Feedback> feedbacks;

    // Getters and Setters

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public List<SpecialityDish> getSpecialityDishes() {
        return specialityDishes;
    }

    public void setSpecialityDishes(List<SpecialityDish> specialityDishes) {
        this.specialityDishes = specialityDishes;
    }

    public List<Feedback> getFeedbacks() {
        return feedbacks;
    }

    public void setFeedbacks(List<Feedback> feedbacks) {
        this.feedbacks = feedbacks;
    }
}