package com.restaurant.model;

import com.github.derjust.spring_data_dynamodb.annotation.DynamoDBHashKey;
import com.github.derjust.spring_data_dynamodb.annotation.DynamoDBTable;
import com.github.derjust.spring_data_dynamodb.annotation.DynamoDBTypeConvertedEnum;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import org.springframework.data.annotation.Id;

import java.util.UUID;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "roles")
public class Role {

    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBTypeConvertedEnum
    private ERole name;

}