package com.restaurant.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.dynamodb.core.mapping.Table;
import org.springframework.data.dynamodb.core.mapping.Attribute;
import org.springframework.data.dynamodb.core.mapping.DynamoDBAutoGeneratedKey;
import org.springframework.data.dynamodb.core.mapping.DynamoDBTypeConvertedEnum;

@Table("roles")
public class Role {

    @Id
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBTypeConvertedEnum
    @Attribute
    private ERole name;

    // Getters and Setters
}