package com.restaurant.model;

import com.github.derjust.spring_data_dynamodb.annotation.DynamoDBHashKey;
import com.github.derjust.spring_data_dynamodb.annotation.DynamoDBTable;
import com.github.derjust.spring_data_dynamodb.annotation.DynamoDBAttribute;
import com.github.derjust.spring_data_dynamodb.annotation.DynamoDBAutoGeneratedKey;
import com.github.derjust.spring_data_dynamodb.annotation.DynamoDBTypeConverted;
import com.github.derjust.spring_data_dynamodb.annotation.DynamoDBTyped;
import com.github.derjust.spring_data_dynamodb.core.DynamoDBTypeConverter;

@DynamoDBTable(tableName = "speciality_dishes")
public class SpecialityDish {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String description;

    @DynamoDBTyped(DynamoDBAttributeType.S)
    private Location location;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Location getLocation() {
        return location;
    }

    public void setLocation(Location location) {
        this.location = location;
    }
}